package main

// Event is entity of input event. 
// This entity is using for validation of structure for input events.
type Event struct {
	Noun           bool    `json:"noun"`
	Attention      string  `json:"attention"`
	Later          bool    `json:"later"`
	Needs          string  `json:"needs"`
	Tightly        string  `json:"tightly"`
	Impossible     bool    `json:"impossible"`
	Dig            string  `json:"dig"`
	Harder         int     `json:"harder"`
	Shorter        bool    `json:"shorter"`
	Loss           int     `json:"loss"`
	Replied        float64 `json:"replied"`
	Rough          bool    `json:"rough"`
	Wonder         float64 `json:"wonder"`
	Someone        float64 `json:"someone"`
	Mostly         int     `json:"mostly"`
	Motion         bool    `json:"motion"`
	Lady           string  `json:"lady"`
	Factor         string  `json:"factor"`
	National       bool    `json:"national"`
	Minute         bool    `json:"minute"`
	Notice         string  `json:"notice"`
	Pond           float64 `json:"pond"`
	Everybody      bool    `json:"everybody"`
	Treated        string  `json:"treated"`
	Railroad       bool    `json:"railroad"`
	However        float64 `json:"however"`
	Skin           bool    `json:"skin"`
	Journey        bool    `json:"journey"`
	Safe           bool    `json:"safe"`
	Describe       bool    `json:"describe"`
	Automobile     string  `json:"automobile"`
	Trip           int     `json:"trip"`
	Furniture      string  `json:"furniture"`
	Recent         bool    `json:"recent"`
	Map            int     `json:"map"`
	Let            string  `json:"let"`
	Ranch          bool    `json:"ranch"`
	Object         bool    `json:"object"`
	Easily         bool    `json:"easily"`
	Anywhere       bool    `json:"anywhere"`
	Coffee         int     `json:"coffee"`
	Won            float64 `json:"won"`
	Instrument     bool    `json:"instrument"`
	Grade          bool    `json:"grade"`
	Perhaps        float64 `json:"perhaps"`
	Vowel          string  `json:"vowel"`
	Probably       float64 `json:"probably"`
	Cookies        string  `json:"cookies"`
	Relationship   bool    `json:"relationship"`
	Involved       string  `json:"involved"`
	Corner         string  `json:"corner"`
	Stand          float64 `json:"stand"`
	Safety         int     `json:"safety"`
	Numeral        bool    `json:"numeral"`
	Adult          bool    `json:"adult"`
	Excited        bool    `json:"excited"`
	Arrangement    int     `json:"arrangement"`
	Seven          float64 `json:"seven"`
	Unit           string  `json:"unit"`
	Pour           string  `json:"pour"`
	Aloud          bool    `json:"aloud"`
	Accurate       string  `json:"accurate"`
	Depend         bool    `json:"depend"`
	Repeat         string  `json:"repeat"`
	Nearby         bool    `json:"nearby"`
	Number         int     `json:"number"`
	Planned        float64 `json:"planned"`
	Fellow         int     `json:"fellow"`
	Organization   bool    `json:"organization"`
	Excellent      string  `json:"excellent"`
	Movement       float64 `json:"movement"`
	Quarter        int     `json:"quarter"`
	Oldest         string  `json:"oldest"`
	Flag           float64 `json:"flag"`
	Story          string  `json:"story"`
	Ball           bool    `json:"ball"`
	Calm           string  `json:"calm"`
	Whistle        string  `json:"whistle"`
	No             float64 `json:"no"`
	Count          int     `json:"count"`
	Especially     string  `json:"especially"`
	Throw          string  `json:"throw"`
	Support        string  `json:"support"`
	Want           int     `json:"want"`
	Mixture        string  `json:"mixture"`
	Thought        string  `json:"thought"`
	Port           bool    `json:"port"`
	Torn           bool    `json:"torn"`
	Row            string  `json:"row"`
	Rhythm         string  `json:"rhythm"`
	Home           bool    `json:"home"`
	Clean          float64 `json:"clean"`
	Vegetable      float64 `json:"vegetable"`
	Seat           bool    `json:"seat"`
	Differ         float64 `json:"differ"`
	Bottom         int     `json:"bottom"`
	Trail          bool    `json:"trail"`
	Him            string  `json:"him"`
	Mistake        int     `json:"mistake"`
	Machine        string  `json:"machine"`
	State          string  `json:"state"`
	Stove          int     `json:"stove"`
	Both           string  `json:"both"`
	Manufacturing  bool    `json:"manufacturing"`
	Section        string  `json:"section"`
	Opportunity    string  `json:"opportunity"`
	Plan           bool    `json:"plan"`
	Change         int     `json:"change"`
	Touch          bool    `json:"touch"`
	Arrange        float64 `json:"arrange"`
	Pleasure       int     `json:"pleasure"`
	Pipe           string  `json:"pipe"`
	Bicycle        float64 `json:"bicycle"`
	Paint          float64 `json:"paint"`
	Vapor          bool    `json:"vapor"`
	Title          bool    `json:"title"`
	Swung          int     `json:"swung"`
	Construction   float64 `json:"construction"`
	Pig            bool    `json:"pig"`
	Duck           string  `json:"duck"`
	Contrast       int     `json:"contrast"`
	Wood           string  `json:"wood"`
	Bar            float64 `json:"bar"`
	Whale          int     `json:"whale"`
	Out            float64 `json:"out"`
	Finest         int     `json:"finest"`
	Brought        string  `json:"brought"`
	Go             string  `json:"go"`
	Why            int     `json:"why"`
	Leave          float64 `json:"leave"`
	Putting        int     `json:"putting"`
	Sick           string  `json:"sick"`
	Nearest        string  `json:"nearest"`
	Hour           string  `json:"hour"`
	Finally        string  `json:"finally"`
	Grass          string  `json:"grass"`
	Act            int     `json:"act"`
	Recall         bool    `json:"recall"`
	Should         float64 `json:"should"`
	Symbol         bool    `json:"symbol"`
	Grow           string  `json:"grow"`
	Onlinetools    bool    `json:"onlinetools"`
	Doing          bool    `json:"doing"`
	Claws          bool    `json:"claws"`
	Stay           bool    `json:"stay"`
	Avoid          int     `json:"avoid"`
	Improve        string  `json:"improve"`
	Gone           string  `json:"gone"`
	Actually       bool    `json:"actually"`
	Work           float64 `json:"work"`
	Lower          bool    `json:"lower"`
	Blind          string  `json:"blind"`
	Classroom      int     `json:"classroom"`
	Pot            float64 `json:"pot"`
	Up             int     `json:"up"`
	Dot            string  `json:"dot"`
	Over           bool    `json:"over"`
	Order          bool    `json:"order"`
	Card           string  `json:"card"`
	Itself         int     `json:"itself"`
	Case           float64 `json:"case"`
	Prove          string  `json:"prove"`
	Smaller        bool    `json:"smaller"`
	Once           bool    `json:"once"`
	Center         bool    `json:"center"`
	Attached       bool    `json:"attached"`
	Reader         float64 `json:"reader"`
	Cat            string  `json:"cat"`
	Gas            string  `json:"gas"`
	Bring          bool    `json:"bring"`
	Fuel           bool    `json:"fuel"`
	Wide           string  `json:"wide"`
	Word           string  `json:"word"`
	Possible       string  `json:"possible"`
	Mother         int     `json:"mother"`
	History        float64 `json:"history"`
	Speed          bool    `json:"speed"`
	Send           string  `json:"send"`
	Find           string  `json:"find"`
	Person         bool    `json:"person"`
	Ordinary       float64 `json:"ordinary"`
	Pound          bool    `json:"pound"`
	Doubt          int     `json:"doubt"`
	Either         int     `json:"either"`
	Farm           string  `json:"farm"`
	Supply         bool    `json:"supply"`
	Snake          string  `json:"snake"`
	Successful     string  `json:"successful"`
	Travel         int     `json:"travel"`
	Soap           bool    `json:"soap"`
	Fly            float64 `json:"fly"`
	Blow           int     `json:"blow"`
	Negative       float64 `json:"negative"`
	Slept          string  `json:"slept"`
	Baseball       bool    `json:"baseball"`
	Stuck          bool    `json:"stuck"`
	Whom           string  `json:"whom"`
	Circle         string  `json:"circle"`
	Physical       bool    `json:"physical"`
	Dawn           bool    `json:"dawn"`
	Paragraph      string  `json:"paragraph"`
	She            int     `json:"she"`
	Mine           float64 `json:"mine"`
	Helpful        string  `json:"helpful"`
	Might          float64 `json:"might"`
	Welcome        bool    `json:"welcome"`
	Flame          string  `json:"flame"`
	Liquid         string  `json:"liquid"`
	Interest       bool    `json:"interest"`
	Military       string  `json:"military"`
	Went           bool    `json:"went"`
	Some           string  `json:"some"`
	Age            string  `json:"age"`
	Morning        bool    `json:"morning"`
	Shade          string  `json:"shade"`
	Same           int     `json:"same"`
	Sail           string  `json:"sail"`
	Boy            bool    `json:"boy"`
	Although       string  `json:"although"`
	Ice            bool    `json:"ice"`
	Century        string  `json:"century"`
	Wall           int     `json:"wall"`
	Back           bool    `json:"back"`
	Command        bool    `json:"command"`
	Thy            bool    `json:"thy"`
	Chain          string  `json:"chain"`
	Held           float64 `json:"held"`
	Condition      bool    `json:"condition"`
	Somebody       bool    `json:"somebody"`
	Type           bool    `json:"type"`
	Four           bool    `json:"four"`
	Human          bool    `json:"human"`
	Baby           string  `json:"baby"`
	Quietly        string  `json:"quietly"`
	Yard           string  `json:"yard"`
	Driven         int     `json:"driven"`
	Refused        int     `json:"refused"`
	Green          float64 `json:"green"`
	Star           int     `json:"star"`
	Hill           float64 `json:"hill"`
	Children       string  `json:"children"`
	Taught         bool    `json:"taught"`
	House          bool    `json:"house"`
	Cannot         float64 `json:"cannot"`
	Wind           bool    `json:"wind"`
	Became         float64 `json:"became"`
	Shelter        string  `json:"shelter"`
	Chemical       float64 `json:"chemical"`
	Properly       int     `json:"properly"`
	Garage         string  `json:"garage"`
	Energy         bool    `json:"energy"`
	Bent           float64 `json:"bent"`
	Meal           bool    `json:"meal"`
	Determine      string  `json:"determine"`
	Orange         int     `json:"orange"`
	Tax            int     `json:"tax"`
	Village        int     `json:"village"`
	Magic          string  `json:"magic"`
	Song           float64 `json:"song"`
	Indicate       string  `json:"indicate"`
	Eager          bool    `json:"eager"`
	Metal          bool    `json:"metal"`
	Frequently     bool    `json:"frequently"`
	Garden         string  `json:"garden"`
	Pine           int     `json:"pine"`
	Fresh          bool    `json:"fresh"`
	Rear           bool    `json:"rear"`
	Universe       string  `json:"universe"`
	Carefully      string  `json:"carefully"`
	Third          string  `json:"third"`
	Wing           string  `json:"wing"`
	Come           string  `json:"come"`
	Paid           bool    `json:"paid"`
	Fill           float64 `json:"fill"`
	Breathe        bool    `json:"breathe"`
	Acres          string  `json:"acres"`
	Game           bool    `json:"game"`
	Topic          int     `json:"topic"`
	Pocket         bool    `json:"pocket"`
	Tool           float64 `json:"tool"`
	Forgot         int     `json:"forgot"`
	Pay            string  `json:"pay"`
	Field          float64 `json:"field"`
	Floating       string  `json:"floating"`
	Exist          bool    `json:"exist"`
	Faster         float64 `json:"faster"`
	Sure           string  `json:"sure"`
	Union          string  `json:"union"`
	Another        bool    `json:"another"`
	Small          bool    `json:"small"`
	Till           bool    `json:"till"`
	Least          string  `json:"least"`
	Unhappy        bool    `json:"unhappy"`
	Music          bool    `json:"music"`
	Means          string  `json:"means"`
	Mill           int     `json:"mill"`
	Brother        string  `json:"brother"`
	Transportation float64 `json:"transportation"`
	Every          string  `json:"every"`
	Atomic         string  `json:"atomic"`
	Given          string  `json:"given"`
	Those          float64 `json:"those"`
	Wife           bool    `json:"wife"`
	Smoke          bool    `json:"smoke"`
	Blood          string  `json:"blood"`
	Bee            string  `json:"bee"`
	Weigh          bool    `json:"weigh"`
	Check          bool    `json:"check"`
	Blue           string  `json:"blue"`
	Unusual        bool    `json:"unusual"`
	May            float64 `json:"may"`
	Serious        string  `json:"serious"`
	Friendly       int     `json:"friendly"`
	Fifty          int     `json:"fifty"`
	Citizen        string  `json:"citizen"`
	Base           bool    `json:"base"`
	Fast           int     `json:"fast"`
	Fierce         string  `json:"fierce"`
	Engineer       bool    `json:"engineer"`
	Smile          int     `json:"smile"`
	Basis          string  `json:"basis"`
	Lying          float64 `json:"lying"`
	Himself        int     `json:"himself"`
	Quick          bool    `json:"quick"`
	Funny          float64 `json:"funny"`
	Largest        string  `json:"largest"`
	Am             string  `json:"am"`
	Few            bool    `json:"few"`
	Forgotten      string  `json:"forgotten"`
	Pole           string  `json:"pole"`
	Desk           float64 `json:"desk"`
	Eventually     string  `json:"eventually"`
	Film           float64 `json:"film"`
	Got            string  `json:"got"`
	Goose          float64 `json:"goose"`
	Getting        bool    `json:"getting"`
	Value          string  `json:"value"`
	Environment    int     `json:"environment"`
	Hungry         string  `json:"hungry"`
	Community      bool    `json:"community"`
	Clothes        string  `json:"clothes"`
	Car            bool    `json:"car"`
	Stems          float64 `json:"stems"`
	Bark           bool    `json:"bark"`
	Mood           bool    `json:"mood"`
	Cool           bool    `json:"cool"`
	Pride          int     `json:"pride"`
	Huge           string  `json:"huge"`
	Six            bool    `json:"six"`
	Slowly         int     `json:"slowly"`
	Shore          int     `json:"shore"`
	Kids           int     `json:"kids"`
	Immediately    int     `json:"immediately"`
	List           string  `json:"list"`
	Cabin          bool    `json:"cabin"`
	Clock          string  `json:"clock"`
	Ran            bool    `json:"ran"`
	Hard           int     `json:"hard"`
	Honor          int     `json:"honor"`
	Split          int     `json:"split"`
	Pull           int     `json:"pull"`
	Page           bool    `json:"page"`
	Lucky          bool    `json:"lucky"`
	Exact          int     `json:"exact"`
	Fought         float64 `json:"fought"`
	Written        string  `json:"written"`
	Syllable       string  `json:"syllable"`
	Writing        bool    `json:"writing"`
	Crew           bool    `json:"crew"`
	Day            string  `json:"day"`
	Watch          bool    `json:"watch"`
	Group          string  `json:"group"`
	Canal          int     `json:"canal"`
	Know           string  `json:"know"`
	Accept         float64 `json:"accept"`
	Carry          string  `json:"carry"`
	Bill           float64 `json:"bill"`
	Thread         int     `json:"thread"`
	Deep           int     `json:"deep"`
	Rhyme          bool    `json:"rhyme"`
	Thin           bool    `json:"thin"`
	Gasoline       string  `json:"gasoline"`
	Younger        bool    `json:"younger"`
	Felt           bool    `json:"felt"`
	Adjective      string  `json:"adjective"`
	Cover          string  `json:"cover"`
	Herd           bool    `json:"herd"`
	Would          float64 `json:"would"`
	Making         bool    `json:"making"`
	Try            float64 `json:"try"`
	Second         bool    `json:"second"`
	General        float64 `json:"general"`
	Folks          string  `json:"folks"`
	Loud           bool    `json:"loud"`
	Death          int     `json:"death"`
	Saw            string  `json:"saw"`
	Chamber        string  `json:"chamber"`
	Grandfather    bool    `json:"grandfather"`
	Note           int     `json:"note"`
	Grandmother    bool    `json:"grandmother"`
	Swim           string  `json:"swim"`
	Important      bool    `json:"important"`
	Belt           float64 `json:"belt"`
	Lovely         float64 `json:"lovely"`
	Week           string  `json:"week"`
	Fireplace      int     `json:"fireplace"`
	Rest           float64 `json:"rest"`
	System         string  `json:"system"`
	Ahead          bool    `json:"ahead"`
	Pack           int     `json:"pack"`
	Frame          string  `json:"frame"`
	Family         int     `json:"family"`
	Shirt          float64 `json:"shirt"`
	Mainly         string  `json:"mainly"`
	Teach          string  `json:"teach"`
	Cry            bool    `json:"cry"`
	Per            int     `json:"per"`
	Voice          string  `json:"voice"`
	Balance        float64 `json:"balance"`
	Men            int     `json:"men"`
	Tune           string  `json:"tune"`
	Horse          string  `json:"horse"`
	Sudden         bool    `json:"sudden"`
	Newspaper      string  `json:"newspaper"`
	Fed            bool    `json:"fed"`
	Individual     bool    `json:"individual"`
	Told           string  `json:"told"`
	Ever           float64 `json:"ever"`
	Wrong          string  `json:"wrong"`
	Bone           int     `json:"bone"`
	Beyond         string  `json:"beyond"`
	Simple         string  `json:"simple"`
	Brush          float64 `json:"brush"`
	Jump           string  `json:"jump"`
	Sent           string  `json:"sent"`
	Police         bool    `json:"police"`
	Bite           bool    `json:"bite"`
	Summer         string  `json:"summer"`
	Recently       float64 `json:"recently"`
	Picture        bool    `json:"picture"`
	Great          string  `json:"great"`
	Box            bool    `json:"box"`
	Flat           bool    `json:"flat"`
	Older          float64 `json:"older"`
	Is             int     `json:"is"`
}
