CREATE DATABASE IF NOT EXISTS ROW_DATA;

CREATE TABLE IF NOT EXISTS ROW_DATA.events 
(
    load_datetime DateTime,
    noun UInt8,
    attention String,
    later UInt8,
    needs String,
    tightly String,
    impossible UInt8,
    dig String,
    harder Int64,
    shorter UInt8,
    loss Int64,
    replied Float64,
    rough UInt8,
    wonder Float64,
    someone Float64,
    mostly Int64,
    motion UInt8,
    lady String,
    factor String,
    national UInt8,
    minute UInt8,
    notice String,
    pond Float64,
    everybody UInt8,
    treated String,
    railroad UInt8,
    however Float64,
    skin UInt8,
    journey UInt8,
    safe UInt8,
    describe UInt8,
    automobile String,
    trip Int64,
    furniture String,
    recent UInt8,
    map Int64,
    let String,
    ranch UInt8,
    object UInt8,
    easily UInt8,
    anywhere UInt8,
    coffee Int64,
    won Float64,
    instrument UInt8,
    grade UInt8,
    perhaps Float64,
    vowel String,
    probably Float64,
    cookies String,
    relationship UInt8,
    involved String,
    corner String,
    stand Float64,
    safety Int64,
    numeral UInt8,
    adult UInt8,
    excited UInt8,
    arrangement Int64,
    seven Float64,
    unit String,
    pour String,
    aloud UInt8,
    accurate String,
    depend UInt8,
    repeat String,
    nearby UInt8,
    number Int64,
    planned Float64,
    fellow Int64,
    organization UInt8,
    excellent String,
    movement Float64,
    quarter Int64,
    oldest String,
    flag Float64,
    story String,
    ball UInt8,
    calm String,
    whistle String,
    no Float64,
    count Int64,
    especially String,
    throw String,
    support String,
    want Int64,
    mixture String,
    thought String,
    port UInt8,
    torn UInt8,
    row String,
    rhythm String,
    home UInt8,
    clean Float64,
    vegetable Float64,
    seat UInt8,
    differ Float64,
    bottom Int64,
    trail UInt8,
    him String,
    mistake Int64,
    machine String,
    state String,
    stove Int64,
    both String,
    manufacturing UInt8,
    section String,
    opportunity String,
    plan UInt8,
    change Int64,
    touch UInt8,
    arrange Float64,
    pleasure Int64,
    pipe String,
    bicycle Float64,
    paint Float64,
    vapor UInt8,
    title UInt8,
    swung Int64,
    construction Float64,
    pig UInt8,
    duck String,
    contrast Int64,
    wood String,
    bar Float64,
    whale Int64,
    out Float64,
    finest Int64,
    brought String,
    go String,
    why Int64,
    leave Float64,
    putting Int64,
    sick String,
    nearest String,
    hour String,
    finally String,
    grass String,
    act Int64,
    recall UInt8,
    should Float64,
    symbol UInt8,
    grow String,
    onlinetools UInt8,
    doing UInt8,
    claws UInt8,
    stay UInt8,
    avoid Int64,
    improve String,
    gone String,
    actually UInt8,
    work Float64,
    lower UInt8,
    blind String,
    classroom Int64,
    pot Float64,
    up Int64,
    dot String,
    over UInt8,
    order UInt8,
    card String,
    itself Int64,
    case Float64,
    prove String,
    smaller UInt8,
    once UInt8,
    center UInt8,
    attached UInt8,
    reader Float64,
    cat String,
    gas String,
    bring UInt8,
    fuel UInt8,
    wide String,
    word String,
    possible String,
    mother Int64,
    history Float64,
    speed UInt8,
    send String,
    find String,
    person UInt8,
    ordinary Float64,
    pound UInt8,
    doubt Int64,
    either Int64,
    farm String,
    supply UInt8,
    snake String,
    successful String,
    travel Int64,
    soap UInt8,
    fly Float64,
    blow Int64,
    negative Float64,
    slept String,
    baseball UInt8,
    stuck UInt8,
    whom String,
    circle String,
    physical UInt8,
    dawn UInt8,
    paragraph String,
    she Int64,
    mine Float64,
    helpful String,
    might Float64,
    welcome UInt8,
    flame String,
    liquid String,
    interest UInt8,
    military String,
    went UInt8,
    some String,
    age String,
    morning UInt8,
    shade String,
    same Int64,
    sail String,
    boy UInt8,
    although String,
    ice UInt8,
    century String,
    wall Int64,
    back UInt8,
    command UInt8,
    thy UInt8,
    chain String,
    held Float64,
    condition UInt8,
    somebody UInt8,
    type UInt8,
    four UInt8,
    human UInt8,
    baby String,
    quietly String,
    yard String,
    driven Int64,
    refused Int64,
    green Float64,
    star Int64,
    hill Float64,
    children String,
    taught UInt8,
    house UInt8,
    cannot Float64,
    wind UInt8,
    became Float64,
    shelter String,
    chemical Float64,
    properly Int64,
    garage String,
    energy UInt8,
    bent Float64,
    meal UInt8,
    determine String,
    orange Int64,
    tax Int64,
    village Int64,
    magic String,
    song Float64,
    indicate String,
    eager UInt8,
    metal UInt8,
    frequently UInt8,
    garden String,
    pine Int64,
    fresh UInt8,
    rear UInt8,
    universe String,
    carefully String,
    third String,
    wing String,
    come String,
    paid UInt8,
    fill Float64,
    breathe UInt8,
    acres String,
    game UInt8,
    topic Int64,
    pocket UInt8,
    tool Float64,
    forgot Int64,
    pay String,
    field Float64,
    floating String,
    exist UInt8,
    faster Float64,
    sure String,
    union String,
    another UInt8,
    small UInt8,
    till UInt8,
    least String,
    unhappy UInt8,
    music UInt8,
    means String,
    mill Int64,
    brother String,
    transportation Float64,
    every String,
    atomic String,
    given String,
    those Float64,
    wife UInt8,
    smoke UInt8,
    blood String,
    bee String,
    weigh UInt8,
    check UInt8,
    blue String,
    unusual UInt8,
    may Float64,
    serious String,
    friendly Int64,
    fifty Int64,
    citizen String,
    base UInt8,
    fast Int64,
    fierce String,
    engineer UInt8,
    smile Int64,
    basis String,
    lying Float64,
    himself Int64,
    quick UInt8,
    funny Float64,
    largest String,
    am String,
    few UInt8,
    forgotten String,
    pole String,
    desk Float64,
    eventually String,
    film Float64,
    got String,
    goose Float64,
    getting UInt8,
    value String,
    environment Int64,
    hungry String,
    community UInt8,
    clothes String,
    car UInt8,
    stems Float64,
    bark UInt8,
    mood UInt8,
    cool UInt8,
    pride Int64,
    huge String,
    six UInt8,
    slowly Int64,
    shore Int64,
    kids Int64,
    immediately Int64,
    list String,
    cabin UInt8,
    clock String,
    ran UInt8,
    hard Int64,
    honor Int64,
    split Int64,
    pull Int64,
    page UInt8,
    lucky UInt8,
    exact Int64,
    fought Float64,
    written String,
    syllable String,
    writing UInt8,
    crew UInt8,
    day String,
    watch UInt8,
    group String,
    canal Int64,
    know String,
    accept Float64,
    carry String,
    bill Float64,
    thread Int64,
    deep Int64,
    rhyme UInt8,
    thin UInt8,
    gasoline String,
    younger UInt8,
    felt UInt8,
    adjective String,
    cover String,
    herd UInt8,
    would Float64,
    making UInt8,
    try Float64,
    second UInt8,
    general Float64,
    folks String,
    loud UInt8,
    death Int64,
    saw String,
    chamber String,
    grandfather UInt8,
    note Int64,
    grandmother UInt8,
    swim String,
    important UInt8,
    belt Float64,
    lovely Float64,
    week String,
    fireplace Int64,
    rest Float64,
    system String,
    ahead UInt8,
    pack Int64,
    frame String,
    family Int64,
    shirt Float64,
    mainly String,
    teach String,
    cry UInt8,
    per Int64,
    voice String,
    balance Float64,
    men Int64,
    tune String,
    horse String,
    sudden UInt8,
    newspaper String,
    fed UInt8,
    individual UInt8,
    told String,
    ever Float64,
    wrong String,
    bone Int64,
    beyond String,
    simple String,
    brush Float64,
    jump String,
    sent String,
    police UInt8,
    bite UInt8,
    summer String,
    recently Float64,
    picture UInt8,
    great String,
    box UInt8,
    flat UInt8,
    older Float64,
    is Int64
) 
ENGINE = MergeTree() 
PARTITION BY load_datetime
ORDER BY load_datetime;

CREATE TABLE IF NOT EXISTS default.events_kafka 
(
    noun UInt8,
    attention String,
    later UInt8,
    needs String,
    tightly String,
    impossible UInt8,
    dig String,
    harder Int64,
    shorter UInt8,
    loss Int64,
    replied Float64,
    rough UInt8,
    wonder Float64,
    someone Float64,
    mostly Int64,
    motion UInt8,
    lady String,
    factor String,
    national UInt8,
    minute UInt8,
    notice String,
    pond Float64,
    everybody UInt8,
    treated String,
    railroad UInt8,
    however Float64,
    skin UInt8,
    journey UInt8,
    safe UInt8,
    describe UInt8,
    automobile String,
    trip Int64,
    furniture String,
    recent UInt8,
    map Int64,
    let String,
    ranch UInt8,
    object UInt8,
    easily UInt8,
    anywhere UInt8,
    coffee Int64,
    won Float64,
    instrument UInt8,
    grade UInt8,
    perhaps Float64,
    vowel String,
    probably Float64,
    cookies String,
    relationship UInt8,
    involved String,
    corner String,
    stand Float64,
    safety Int64,
    numeral UInt8,
    adult UInt8,
    excited UInt8,
    arrangement Int64,
    seven Float64,
    unit String,
    pour String,
    aloud UInt8,
    accurate String,
    depend UInt8,
    repeat String,
    nearby UInt8,
    number Int64,
    planned Float64,
    fellow Int64,
    organization UInt8,
    excellent String,
    movement Float64,
    quarter Int64,
    oldest String,
    flag Float64,
    story String,
    ball UInt8,
    calm String,
    whistle String,
    no Float64,
    count Int64,
    especially String,
    throw String,
    support String,
    want Int64,
    mixture String,
    thought String,
    port UInt8,
    torn UInt8,
    row String,
    rhythm String,
    home UInt8,
    clean Float64,
    vegetable Float64,
    seat UInt8,
    differ Float64,
    bottom Int64,
    trail UInt8,
    him String,
    mistake Int64,
    machine String,
    state String,
    stove Int64,
    both String,
    manufacturing UInt8,
    section String,
    opportunity String,
    plan UInt8,
    change Int64,
    touch UInt8,
    arrange Float64,
    pleasure Int64,
    pipe String,
    bicycle Float64,
    paint Float64,
    vapor UInt8,
    title UInt8,
    swung Int64,
    construction Float64,
    pig UInt8,
    duck String,
    contrast Int64,
    wood String,
    bar Float64,
    whale Int64,
    out Float64,
    finest Int64,
    brought String,
    go String,
    why Int64,
    leave Float64,
    putting Int64,
    sick String,
    nearest String,
    hour String,
    finally String,
    grass String,
    act Int64,
    recall UInt8,
    should Float64,
    symbol UInt8,
    grow String,
    onlinetools UInt8,
    doing UInt8,
    claws UInt8,
    stay UInt8,
    avoid Int64,
    improve String,
    gone String,
    actually UInt8,
    work Float64,
    lower UInt8,
    blind String,
    classroom Int64,
    pot Float64,
    up Int64,
    dot String,
    over UInt8,
    order UInt8,
    card String,
    itself Int64,
    case Float64,
    prove String,
    smaller UInt8,
    once UInt8,
    center UInt8,
    attached UInt8,
    reader Float64,
    cat String,
    gas String,
    bring UInt8,
    fuel UInt8,
    wide String,
    word String,
    possible String,
    mother Int64,
    history Float64,
    speed UInt8,
    send String,
    find String,
    person UInt8,
    ordinary Float64,
    pound UInt8,
    doubt Int64,
    either Int64,
    farm String,
    supply UInt8,
    snake String,
    successful String,
    travel Int64,
    soap UInt8,
    fly Float64,
    blow Int64,
    negative Float64,
    slept String,
    baseball UInt8,
    stuck UInt8,
    whom String,
    circle String,
    physical UInt8,
    dawn UInt8,
    paragraph String,
    she Int64,
    mine Float64,
    helpful String,
    might Float64,
    welcome UInt8,
    flame String,
    liquid String,
    interest UInt8,
    military String,
    went UInt8,
    some String,
    age String,
    morning UInt8,
    shade String,
    same Int64,
    sail String,
    boy UInt8,
    although String,
    ice UInt8,
    century String,
    wall Int64,
    back UInt8,
    command UInt8,
    thy UInt8,
    chain String,
    held Float64,
    condition UInt8,
    somebody UInt8,
    type UInt8,
    four UInt8,
    human UInt8,
    baby String,
    quietly String,
    yard String,
    driven Int64,
    refused Int64,
    green Float64,
    star Int64,
    hill Float64,
    children String,
    taught UInt8,
    house UInt8,
    cannot Float64,
    wind UInt8,
    became Float64,
    shelter String,
    chemical Float64,
    properly Int64,
    garage String,
    energy UInt8,
    bent Float64,
    meal UInt8,
    determine String,
    orange Int64,
    tax Int64,
    village Int64,
    magic String,
    song Float64,
    indicate String,
    eager UInt8,
    metal UInt8,
    frequently UInt8,
    garden String,
    pine Int64,
    fresh UInt8,
    rear UInt8,
    universe String,
    carefully String,
    third String,
    wing String,
    come String,
    paid UInt8,
    fill Float64,
    breathe UInt8,
    acres String,
    game UInt8,
    topic Int64,
    pocket UInt8,
    tool Float64,
    forgot Int64,
    pay String,
    field Float64,
    floating String,
    exist UInt8,
    faster Float64,
    sure String,
    union String,
    another UInt8,
    small UInt8,
    till UInt8,
    least String,
    unhappy UInt8,
    music UInt8,
    means String,
    mill Int64,
    brother String,
    transportation Float64,
    every String,
    atomic String,
    given String,
    those Float64,
    wife UInt8,
    smoke UInt8,
    blood String,
    bee String,
    weigh UInt8,
    check UInt8,
    blue String,
    unusual UInt8,
    may Float64,
    serious String,
    friendly Int64,
    fifty Int64,
    citizen String,
    base UInt8,
    fast Int64,
    fierce String,
    engineer UInt8,
    smile Int64,
    basis String,
    lying Float64,
    himself Int64,
    quick UInt8,
    funny Float64,
    largest String,
    am String,
    few UInt8,
    forgotten String,
    pole String,
    desk Float64,
    eventually String,
    film Float64,
    got String,
    goose Float64,
    getting UInt8,
    value String,
    environment Int64,
    hungry String,
    community UInt8,
    clothes String,
    car UInt8,
    stems Float64,
    bark UInt8,
    mood UInt8,
    cool UInt8,
    pride Int64,
    huge String,
    six UInt8,
    slowly Int64,
    shore Int64,
    kids Int64,
    immediately Int64,
    list String,
    cabin UInt8,
    clock String,
    ran UInt8,
    hard Int64,
    honor Int64,
    split Int64,
    pull Int64,
    page UInt8,
    lucky UInt8,
    exact Int64,
    fought Float64,
    written String,
    syllable String,
    writing UInt8,
    crew UInt8,
    day String,
    watch UInt8,
    group String,
    canal Int64,
    know String,
    accept Float64,
    carry String,
    bill Float64,
    thread Int64,
    deep Int64,
    rhyme UInt8,
    thin UInt8,
    gasoline String,
    younger UInt8,
    felt UInt8,
    adjective String,
    cover String,
    herd UInt8,
    would Float64,
    making UInt8,
    try Float64,
    second UInt8,
    general Float64,
    folks String,
    loud UInt8,
    death Int64,
    saw String,
    chamber String,
    grandfather UInt8,
    note Int64,
    grandmother UInt8,
    swim String,
    important UInt8,
    belt Float64,
    lovely Float64,
    week String,
    fireplace Int64,
    rest Float64,
    system String,
    ahead UInt8,
    pack Int64,
    frame String,
    family Int64,
    shirt Float64,
    mainly String,
    teach String,
    cry UInt8,
    per Int64,
    voice String,
    balance Float64,
    men Int64,
    tune String,
    horse String,
    sudden UInt8,
    newspaper String,
    fed UInt8,
    individual UInt8,
    told String,
    ever Float64,
    wrong String,
    bone Int64,
    beyond String,
    simple String,
    brush Float64,
    jump String,
    sent String,
    police UInt8,
    bite UInt8,
    summer String,
    recently Float64,
    picture UInt8,
    great String,
    box UInt8,
    flat UInt8,
    older Float64,
    is Int64
)  
ENGINE = Kafka()
SETTINGS
    kafka_broker_list = 'kafka:9192',
    kafka_topic_list = 'events_topic',
    kafka_group_name = 'clickcouse_reader',
    kafka_format = 'JSONEachRow',
    kafka_num_consumers = 1
;

CREATE MATERIALIZED VIEW IF NOT EXISTS default.events_consumer TO ROW_DATA.events AS 
    SELECT
        now() as load_datetime,
        noun,
        attention,
        later,
        needs,
        tightly,
        impossible,
        dig,
        harder,
        shorter,
        loss,
        replied,
        rough,
        wonder,
        someone,
        mostly,
        motion,
        lady,
        factor,
        national,
        minute,
        notice,
        pond,
        everybody,
        treated,
        railroad,
        however,
        skin,
        journey,
        safe,
        describe,
        automobile,
        trip,
        furniture,
        recent,
        map,
        let,
        ranch,
        object,
        easily,
        anywhere,
        coffee,
        won,
        instrument,
        grade,
        perhaps,
        vowel,
        probably,
        cookies,
        relationship,
        involved,
        corner,
        stand,
        safety,
        numeral,
        adult,
        excited,
        arrangement,
        seven,
        unit,
        pour,
        aloud,
        accurate,
        depend,
        repeat,
        nearby,
        number,
        planned,
        fellow,
        organization,
        excellent,
        movement,
        quarter,
        oldest,
        flag,
        story,
        ball,
        calm,
        whistle,
        no,
        count,
        especially,
        throw,
        support,
        want,
        mixture,
        thought,
        port,
        torn,
        row,
        rhythm,
        home,
        clean,
        vegetable,
        seat,
        differ,
        bottom,
        trail,
        him,
        mistake,
        machine,
        state,
        stove,
        both,
        manufacturing,
        section,
        opportunity,
        plan,
        change,
        touch,
        arrange,
        pleasure,
        pipe,
        bicycle,
        paint,
        vapor,
        title,
        swung,
        construction,
        pig,
        duck,
        contrast,
        wood,
        bar,
        whale,
        out,
        finest,
        brought,
        go,
        why,
        leave,
        putting,
        sick,
        nearest,
        hour,
        finally,
        grass,
        act,
        recall,
        should,
        symbol,
        grow,
        onlinetools,
        doing,
        claws,
        stay,
        avoid,
        improve,
        gone,
        actually,
        work,
        lower,
        blind,
        classroom,
        pot,
        up,
        dot,
        over,
        order,
        card,
        itself,
        case,
        prove,
        smaller,
        once,
        center,
        attached,
        reader,
        cat,
        gas,
        bring,
        fuel,
        wide,
        word,
        possible,
        mother,
        history,
        speed,
        send,
        find,
        person,
        ordinary,
        pound,
        doubt,
        either,
        farm,
        supply,
        snake,
        successful,
        travel,
        soap,
        fly,
        blow,
        negative,
        slept,
        baseball,
        stuck,
        whom,
        circle,
        physical,
        dawn,
        paragraph,
        she,
        mine,
        helpful,
        might,
        welcome,
        flame,
        liquid,
        interest,
        military,
        went,
        some,
        age,
        morning,
        shade,
        same,
        sail,
        boy,
        although,
        ice,
        century,
        wall,
        back,
        command,
        thy,
        chain,
        held,
        condition,
        somebody,
        type,
        four,
        human,
        baby,
        quietly,
        yard,
        driven,
        refused,
        green,
        star,
        hill,
        children,
        taught,
        house,
        cannot,
        wind,
        became,
        shelter,
        chemical,
        properly,
        garage,
        energy,
        bent,
        meal,
        determine,
        orange,
        tax,
        village,
        magic,
        song,
        indicate,
        eager,
        metal,
        frequently,
        garden,
        pine,
        fresh,
        rear,
        universe,
        carefully,
        third,
        wing,
        come,
        paid,
        fill,
        breathe,
        acres,
        game,
        topic,
        pocket,
        tool,
        forgot,
        pay,
        field,
        floating,
        exist,
        faster,
        sure,
        union,
        another,
        small,
        till,
        least,
        unhappy,
        music,
        means,
        mill,
        brother,
        transportation,
        every,
        atomic,
        given,
        those,
        wife,
        smoke,
        blood,
        bee,
        weigh,
        check,
        blue,
        unusual,
        may,
        serious,
        friendly,
        fifty,
        citizen,
        base,
        fast,
        fierce,
        engineer,
        smile,
        basis,
        lying,
        himself,
        quick,
        funny,
        largest,
        am,
        few,
        forgotten,
        pole,
        desk,
        eventually,
        film,
        got,
        goose,
        getting,
        value,
        environment,
        hungry,
        community,
        clothes,
        car,
        stems,
        bark,
        mood,
        cool,
        pride,
        huge,
        six,
        slowly,
        shore,
        kids,
        immediately,
        list,
        cabin,
        clock,
        ran,
        hard,
        honor,
        split,
        pull,
        page,
        lucky,
        exact,
        fought,
        written,
        syllable,
        writing,
        crew,
        day,
        watch,
        group,
        canal,
        know,
        accept,
        carry,
        bill,
        thread,
        deep,
        rhyme,
        thin,
        gasoline,
        younger,
        felt,
        adjective,
        cover,
        herd,
        would,
        making,
        try,
        second,
        general,
        folks,
        loud,
        death,
        saw,
        chamber,
        grandfather,
        note,
        grandmother,
        swim,
        important,
        belt,
        lovely,
        week,
        fireplace,
        rest,
        system,
        ahead,
        pack,
        frame,
        family,
        shirt,
        mainly,
        teach,
        cry,
        per,
        voice,
        balance,
        men,
        tune,
        horse,
        sudden,
        newspaper,
        fed,
        individual,
        told,
        ever,
        wrong,
        bone,
        beyond,
        simple,
        brush,
        jump,
        sent,
        police,
        bite,
        summer,
        recently,
        picture,
        great,
        box,
        flat,
        older,
        is
    FROM default.events_kafka;
